DROP TABLE IF EXISTS WASH_data;

CREATE TABLE WASH_data AS (
	SELECT c.COUNTRY, CONTINENT, p.YEAR, p.GRANULARITY, POPULATION, CAST(SURFACE AS FLOAT) AS SURF_AREA, 
		CAST(MORTALITY_RATE_UNSAFE_WATER AS FLOAT) AS MORTALITY_RATE_UNSAFE_WATER, 
		CAST(DEATHS AS FLOAT) AS DEATHS, STABILITY, CAST(BASIC AS FLOAT) AS BASIC, CAST(SAFELY_MANAGED AS FLOAT) AS SAFELY_MANAGED
	FROM COUNTRY c
	LEFT OUTER JOIN population p ON c.COUNTRY = UPPER(p.COUNTRY)
    LEFT OUTER JOIN region r ON c.COUNTRY=UPPER(r.COUNTRY)
    LEFT OUTER JOIN mortality m ON c.COUNTRY=UPPER(m.COUNTRY) AND p.YEAR = m.YEAR AND p.GRANULARITY = m.GRANULARITY
	LEFT OUTER JOIN political_stability s ON c.COUNTRY=UPPER(s.COUNTRY) AND p.YEAR = s.YEAR AND p.GRANULARITY = s.GRANULARITY
	LEFT OUTER JOIN dw_services dw ON c.COUNTRY=UPPER(dw.COUNTRY) AND p.YEAR = dw.YEAR AND p.GRANULARITY = dw.GRANULARITY
    LEFT OUTER JOIN surface_area a ON c.COUNTRY = UPPER(a.COUNTRY) AND p.GRANULARITY = 'Total'
    WHERE CONTINENT IS NOT NULL
    );
    