DROP TABLE IF EXISTS country;

CREATE TABLE country AS (
SELECT UPPER(COUNTRY) as COUNTRY FROM population
UNION DISTINCT 
SELECT UPPER(COUNTRY) as COUNTRY FROM region
UNION DISTINCT 
SELECT UPPER(COUNTRY) as COUNTRY FROM political_stability
UNION DISTINCT 
SELECT UPPER(COUNTRY) as COUNTRY FROM mortality
UNION DISTINCT 
SELECT UPPER(COUNTRY) as COUNTRY FROM surface_area
);